# -*- coding: utf-8 -*-
"""SHDB-AF: a Japanese Holter ECG Database of Atrial Fibrillation - NSR Extraction Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLUzEjDd0Ea9jdaki4YD3npKkK4mj8fK
"""



!pip install wfdb

# =============================================================================
# SHDB-AF Preprocessing Pipeline  |  Steps 1–4
# Master's Thesis: Deep Learning for Predicting Atrial Fibrillation
# =============================================================================
#
# PURPOSE:
#   This script implements the full data preprocessing pipeline as specified
#   in the Master Experiment Specification Document. It produces four JSON
#   files that act as temporal index pointers into the raw ECG recordings.
#   No signal data is loaded, stored, or manipulated here.
#
# OUTPUT FILES:
#   step1_output.json  —  filtering log + usable_patients
#   step2_output.json  —  step_2_log  + af_free_regions
#   step3_output.json  —  config + train/eval split + step_3_log
#   step4_output.json  —  config + train_windows + eval_windows + step_4_log
#
# NOTE ON TERMINOLOGY:
#   The specification uses "eval" set. This is the test set for the experiment.
#   All JSON keys and variable names use "eval" to match the spec exactly.
#
# USAGE:
#   1. Mount Google Drive (cell runs automatically in Colab).
#   2. Edit the CONFIG dict in Section 0 — paths and column names only.
#   3. Run all cells top to bottom.
#
# =============================================================================

# %% ── SECTION 0: Imports, Configuration, Reproducibility, Drive Mount ────────

import os
import json
import math
import random
import hashlib
import numpy as np
import pandas as pd
import wfdb
from datetime import datetime, timezone

# ── Google Drive Mount ────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')


# ── Reproducibility ───────────────────────────────────────────────────────────

def set_global_seed(seed: int) -> None:
    """
    Set all random seeds at the global level.

    This covers numpy, Python's random module, and the OS-level hash seed.
    Per-region seeds used in Step 4 are derived independently via
    _derive_region_seed() and do not consume or disturb this global state —
    they operate through isolated random.Random instances.
    """
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)


# ── Configuration ─────────────────────────────────────────────────────────────
# This is the ONLY section you should edit.
#
# COLUMN NAMES: Set to the spec's naming conventions as defaults.
# Verify each one against your actual AdditionalData.csv header row and
# correct here if they differ. A clear assertion in Step 1 will tell you
# exactly which columns are missing if names are wrong.
#
# AF TYPE LABELS: Verify that "PAF", "PerAF", "non_AF" match the exact
# string values in your AF_Type column.

CONFIG = {

    # ── File paths ─────────────────────────────────────────────────────────
    "csv_path":   "/content/drive/My Drive/shdb-af/AdditionalData.csv", # Add your path in Google Drive Here
    "wfdb_dir":   "/content/drive/My Drive/shdb-af",   # folder with .dat/.hea/.atr files
    "output_dir": "/content/drive/My Drive/shdb-af/pipeline_output",

    # ── CSV column names — VERIFY AGAINST YOUR ACTUAL CSV HEADER ──────────
    "col_subject_id":       "Subject_ID",
    "col_data_id":          "Data_ID",
    "col_af_type":          "AF_Type",
    "col_annotated":        "Annotated",
    "col_recording_length": "Holter_recording_length",   # expected format: HH:MM:SS

    # ── AF type label values — VERIFY AGAINST YOUR ACTUAL CSV VALUES ───────
    "label_paf":    "PAF",
    "label_per_af": "PerAF",
    "label_non_af": "non_AF",

    # ── Signal ────────────────────────────────────────────────────────────
    "sampling_rate": 200,   # Hz — SHDB-AF resampled rate

    # ── Step 2: trim and buffer durations (seconds) ────────────────────────
    # T: recording edge trim — applied to the start AND end of every
    #    recording for all patients (both PAF and non-AF).
    # X: pre-AF buffer — removed from the END of an N region that is
    #    immediately followed by an AFIB episode (PAF patients only).
    # Y: post-AF buffer — removed from the START of an N region that is
    #    immediately preceded by an AFIB episode (PAF patients only).
    "T": 300.0,
    "X": 300.0,
    "Y": 300.0,

    # ── Step 3 ────────────────────────────────────────────────────────────
    # DT: the non-overlapping window duration used to count how many windows
    #     fit per region (floor division). Patients with zero windows are
    #     ineligible. Also the window extracted per patient in Step 4.
    # eval_fraction: proportion of each class assigned to the eval (test) set.
    # random_seed: base seed for all deterministic selections in Steps 3 & 4.
    "DT":            600.0,
    "eval_fraction":  0.2,
    "random_seed":    42,

    # ── Step 4 ────────────────────────────────────────────────────────────
    # D:  sub-window duration in seconds.
    # Pt: fractional overlap between consecutive sub-windows in the train set.
    # Pe: fractional overlap between consecutive sub-windows in the eval set.
    "D":  60.0,
    "Pt": 0.5,
    "Pe": 0.0,
}

set_global_seed(CONFIG["random_seed"])
os.makedirs(CONFIG["output_dir"], exist_ok=True)

print("=== CONFIG (non-path keys) ===")
print(json.dumps(
    {k: v for k, v in CONFIG.items() if "path" not in k and "dir" not in k},
    indent=2
))

# %% ── SECTION 1: Step 1 — Filtering ─────────────────────────────────────────

def hms_to_seconds(hms: str) -> float:
    """
    Convert a recording duration string from HH:MM:SS format to total seconds.

    Example: "23:32:00" → 84720.0

    The Holter_recording_length column stores values in this format.
    Raises ValueError with a descriptive message if the format is unexpected,
    so bad rows are caught early rather than silently propagating wrong durations.
    """
    parts = str(hms).strip().split(":")
    if len(parts) != 3:
        raise ValueError(
            f"Unexpected recording length format: '{hms}'. "
            "Expected HH:MM:SS (e.g. '23:32:00')."
        )
    h, m, s = int(parts[0]), int(parts[1]), float(parts[2])
    return h * 3600.0 + m * 60.0 + s


def run_step1_filtering(config: dict) -> dict:
    """
    Step 1: Read AdditionalData.csv and produce the usable patient pool.

    Sub-steps:
      1.i   — Remove all PerAF patients.
      1.ii  — Remove unannotated recordings. Patients whose every recording
              is unannotated are removed entirely (Case A). Patients with at
              least one annotated recording survive, but only their annotated
              recordings are kept (Case B).
      1.iii — Build the final usable_patients dictionary with recording
              durations converted from HH:MM:SS to seconds.

    Design note: the CSV is read with dtype=str throughout to prevent pandas
    from silently casting Data_ID integers (e.g. 1 → "1") in ways that could
    cause mismatches with the zero-padded filenames ("001"). String normalisation
    happens explicitly here and in _data_id_to_record_name() in Step 2.

    Returns
    -------
    dict with keys: filtering_log, usable_patients
    """
    # ── Read CSV — all columns as strings to preserve Data_ID leading zeros ──
    df = pd.read_csv(config["csv_path"], dtype=str)

    # ── Column presence check — catches wrong config names immediately ────────
    required_cols = [
        config["col_subject_id"],
        config["col_data_id"],
        config["col_af_type"],
        config["col_annotated"],
        config["col_recording_length"],
    ]
    missing = [c for c in required_cols if c not in df.columns]
    assert not missing, (
        f"\n[Step 1] COLUMN MISMATCH — these columns from CONFIG were not found in the CSV:\n"
        f"  Missing: {missing}\n"
        f"  Actual CSV columns: {list(df.columns)}\n"
        f"Fix the col_* keys in CONFIG to match your CSV exactly."
    )

    # Strip leading/trailing whitespace from all string-typed columns
    for col in required_cols:
        df[col] = df[col].str.strip()

    # Parse the Annotated column — handles "True"/"False" strings or "1"/"0"
    df["_annotated_bool"] = df[config["col_annotated"]].str.lower().isin(
        ("true", "1", "yes")
    )

    filtering_log  = {}
    label_paf    = config["label_paf"]
    label_per_af = config["label_per_af"]
    label_non_af = config["label_non_af"]
    col_subj = config["col_subject_id"]
    col_data = config["col_data_id"]
    col_af   = config["col_af_type"]

    # ── Step 1.i: Remove PerAF patients ──────────────────────────────────────
    per_af_mask = df[col_af] == label_per_af
    per_af_df   = df[per_af_mask].copy()
    df          = df[~per_af_mask].copy()

    removed_1i = {}
    for subj, grp in per_af_df.groupby(col_subj):
        removed_1i[str(subj)] = {
            "af_type":            label_per_af,
            "recordings_removed": sorted(grp[col_data].tolist()),
        }

    after_1i_total   = df[col_subj].nunique()
    after_1i_paf     = df[df[col_af] == label_paf][col_subj].nunique()
    after_1i_non_af  = df[df[col_af] == label_non_af][col_subj].nunique()

    filtering_log["step_1i_perAF_removed"] = {
        "patients_removed":   len(removed_1i),
        "recordings_removed": int(per_af_df.shape[0]),
        "removed_subjects":   removed_1i,
        "remaining_after_removal": {
            "total_patients":  after_1i_total,
            "PAF_patients":    after_1i_paf,
            "non_AF_patients": after_1i_non_af,
        },
    }

    # ── Step 1.ii: Remove unannotated recordings ──────────────────────────────
    annotated_df   = df[df["_annotated_bool"]].copy()
    unannotated_df = df[~df["_annotated_bool"]].copy()

    subjects_with_annotated   = set(annotated_df[col_subj].unique())
    subjects_with_unannotated = set(unannotated_df[col_subj].unique())

    # Case A: patient has NO annotated recording at all → remove entire patient
    fully_removed_subjects = subjects_with_unannotated - subjects_with_annotated
    # Case B: patient has at least one annotated recording → keep patient,
    #         drop only the unannotated recording(s)
    partially_affected_subjects = subjects_with_unannotated & subjects_with_annotated

    patients_fully_removed = {}
    for subj in sorted(fully_removed_subjects):
        af_type  = df.loc[df[col_subj] == subj, col_af].iloc[0]
        recs_all = sorted(df.loc[df[col_subj] == subj, col_data].tolist())
        patients_fully_removed[str(subj)] = {
            "af_type":            af_type,
            "recordings_removed": recs_all,
        }

    recordings_only_removed = {}
    count_recs_only   = 0
    count_recs_paf    = 0
    count_recs_non_af = 0
    for subj in sorted(partially_affected_subjects):
        af_type    = df.loc[df[col_subj] == subj, col_af].iloc[0]
        recs_dropped = sorted(
            unannotated_df.loc[unannotated_df[col_subj] == subj, col_data].tolist()
        )
        recordings_only_removed[str(subj)] = {
            "af_type":            af_type,
            "recordings_removed": recs_dropped,
        }
        n = len(recs_dropped)
        count_recs_only += n
        if af_type == label_paf:
            count_recs_paf += n
        else:
            count_recs_non_af += n

    fr_paf    = sum(1 for v in patients_fully_removed.values() if v["af_type"] == label_paf)
    fr_non_af = len(patients_fully_removed) - fr_paf

    filtering_log["step_1ii_no_atr_removed"] = {
        "patients_fully_removed": {
            "total_patients_removed":  len(patients_fully_removed),
            "PAF_patients_removed":    fr_paf,
            "non_AF_patients_removed": fr_non_af,
            "subjects":                patients_fully_removed,
        },
        "recordings_only_removed": {
            "total_recordings_removed":        count_recs_only,
            "recordings_from_PAF_patients":    count_recs_paf,
            "recordings_from_non_AF_patients": count_recs_non_af,
            "subjects":                        recordings_only_removed,
        },
    }

    # Retain only annotated recordings; remove fully-dropped patients
    df = annotated_df[~annotated_df[col_subj].isin(fully_removed_subjects)].copy()

    # ── Step 1.iii: Build usable_patients ─────────────────────────────────────
    total_patients  = df[col_subj].nunique()
    paf_patients    = df[df[col_af] == label_paf][col_subj].nunique()
    non_af_patients = df[df[col_af] == label_non_af][col_subj].nunique()
    total_recs      = df.shape[0]
    paf_recs        = df[df[col_af] == label_paf].shape[0]
    non_af_recs     = df[df[col_af] == label_non_af].shape[0]

    filtering_log["step_1iii_usable_pool_summary"] = {
        "total_patients":    total_patients,
        "PAF_patients":      paf_patients,
        "non_AF_patients":   non_af_patients,
        "total_recordings":  total_recs,
        "PAF_recordings":    paf_recs,
        "non_AF_recordings": non_af_recs,
    }

    usable_patients = {}
    for subj, grp in df.groupby(col_subj):
        af_type    = grp[col_af].iloc[0]
        recordings = {}
        for _, row in grp.iterrows():
            data_id      = str(row[col_data])
            duration_sec = hms_to_seconds(row[config["col_recording_length"]])
            recordings[data_id] = {"recording_duration_sec": duration_sec}
        usable_patients[str(subj)] = {
            "af_type":          af_type,
            "total_recordings": len(recordings),
            "recordings":       recordings,
        }

    # Sanity check
    assert len(usable_patients) == total_patients, (
        f"[Step 1] Patient count mismatch: usable_patients has {len(usable_patients)}, "
        f"expected {total_patients}."
    )

    step1_output = {
        "filtering_log":   filtering_log,
        "usable_patients": usable_patients,
    }

    print(f"[Step 1] Usable patients:   {total_patients} ({paf_patients} PAF, {non_af_patients} non-AF)")
    print(f"[Step 1] Usable recordings: {total_recs}")

    return step1_output

# %% ── SECTION 2: Step 2 — AF-Free Region Extraction ─────────────────────────

def _data_id_to_record_name(data_id: str) -> str:
    """
    Convert a Data_ID string to the zero-padded 3-digit record stem used
    on disk.

    The SHDB-AF files are named 001.atr, 002.atr, ..., 128.atr.
    The CSV may store Data_ID as "1", "01", or "001" depending on how it
    was created. int() normalises all of these; zfill(3) pads back to 3
    digits.

    Examples:
      "1"   → "001"
      "12"  → "012"
      "104" → "104"
    """
    return str(int(data_id)).zfill(3)


def _parse_annotation_intervals(
    record_path: str,
    recording_duration_sec: float,
    sampling_rate: int,
) -> list:
    """
    Parse a WFDB .atr rhythm annotation file and return a list of
    (start_sec, end_sec, rhythm_label) tuples that cover the full recording.

    WFDB stores rhythm change labels in ann.aux_note with a leading '('
    character (e.g. '(AFIB', '(N', '(AFL'). Each entry marks the START
    of a new rhythm segment; the end of segment i is the start of segment i+1,
    or recording_duration_sec for the final segment.

    Cleaning applied to each aux_note entry:
      - Strip null bytes (\x00) — common WFDB artifact
      - Strip leading/trailing whitespace
      - Strip the leading '(' character

    Consecutive N annotations are merged into a single N segment. This
    handles any pathological case where N is re-annotated mid-segment
    without an intervening rhythm change.

    Parameters
    ----------
    record_path          : full path to the record WITHOUT extension
                           (wfdb.rdann appends .atr automatically)
    recording_duration_sec : duration from the CSV (Step 1), used as the
                             end time of the final rhythm segment
    sampling_rate        : samples per second (200 Hz for SHDB-AF)

    Returns
    -------
    List of (start_sec: float, end_sec: float, rhythm_label: str) tuples
    in chronological order. Empty list if no rhythm annotations are found.
    """
    ann = wfdb.rdann(record_path, 'atr')

    # Extract rhythm transitions: only entries where aux_note is non-empty
    # after cleaning are rhythm label markers.
    transitions = []
    for sample, note in zip(ann.sample, ann.aux_note):
        clean = note.replace('\x00', '').strip().lstrip('(').strip()
        if clean:
            transitions.append((int(sample), clean))

    if not transitions:
        return []

    # Build (start_sec, end_sec, rhythm) interval list
    intervals = []
    for i, (sample, rhythm) in enumerate(transitions):
        start_sec = sample / sampling_rate
        if i + 1 < len(transitions):
            end_sec = transitions[i + 1][0] / sampling_rate
        else:
            end_sec = recording_duration_sec
        intervals.append([start_sec, end_sec, rhythm])

    # Merge consecutive N segments (handles re-annotation artefacts)
    merged = []
    for seg in intervals:
        if merged and merged[-1][2] == 'N' and seg[2] == 'N':
            merged[-1][1] = seg[1]   # extend the end of the previous N segment
        else:
            merged.append(seg)

    return [tuple(s) for s in merged]


def _extract_n_regions(
    intervals: list,
    af_type: str,
    T: float,
    X: float,
    Y: float,
    recording_duration_sec: float,
    label_paf: str,
) -> list:
    """
    Apply recording edge trim (T) and AFIB safety buffers (X, Y) to all
    N segments in the interval list and return surviving usable regions.

    Design decisions implemented here:
    - T is applied to ALL patients (PAF and non-AF) as a recording-level
      boundary: recording_usable_start = T, recording_usable_end = duration - T.
    - X and Y buffers are applied ONLY to PAF patients, and ONLY on the
      edge of an N region immediately adjacent to an AFIB segment.
    - Clamping: both the trim boundary and the buffer boundary constrain
      the same edge independently; the more restrictive one wins.
      usable_start = max(region_start, recording_usable_start, buffer_start)
      usable_end   = min(region_end,   recording_usable_end,   buffer_end)
    - Regions where usable_end <= usable_start after clamping are discarded.

    Parameters
    ----------
    intervals  : output of _parse_annotation_intervals
    af_type    : patient's AF type — buffers are only applied if == label_paf
    T, X, Y    : trim and buffer durations in seconds (from CONFIG)
    recording_duration_sec : total recording length in seconds
    label_paf  : the PAF label string from CONFIG

    Returns
    -------
    List of dicts with keys: start_sec, end_sec, duration_sec.
    Listed in chronological order (ascending start_sec).
    Empty list if no region survives.
    """
    recording_usable_start = T
    recording_usable_end   = recording_duration_sec - T
    is_paf = (af_type == label_paf)

    surviving = []

    for i, (seg_start, seg_end, rhythm) in enumerate(intervals):
        if rhythm != 'N':
            continue

        # Determine AFIB adjacency — only matters for PAF patients
        # "Immediate" means the directly adjacent segment in the interval list.
        preceded_by_afib = False
        followed_by_afib = False
        if is_paf:
            if i > 0 and intervals[i - 1][2] == 'AFIB':
                preceded_by_afib = True
            if i < len(intervals) - 1 and intervals[i + 1][2] == 'AFIB':
                followed_by_afib = True

        # --- Compute usable_start ---
        # Start is pushed inward by whichever boundary is most restrictive:
        # the region's own start, the recording trim, or the post-AF buffer.
        usable_start = seg_start
        usable_start = max(usable_start, recording_usable_start)
        if preceded_by_afib:
            # Post-AF buffer Y pushes start of this N region inward
            usable_start = max(usable_start, seg_start + Y)

        # --- Compute usable_end ---
        usable_end = seg_end
        usable_end = min(usable_end, recording_usable_end)
        if followed_by_afib:
            # Pre-AF buffer X pushes end of this N region inward
            usable_end = min(usable_end, seg_end - X)

        # Validity check: discard zero- or negative-duration regions
        if usable_end <= usable_start:
            continue

        surviving.append({
            "start_sec":    round(usable_start, 6),
            "end_sec":      round(usable_end,   6),
            "duration_sec": round(usable_end - usable_start, 6),
        })

    # Chronological order is preserved because intervals are already sorted
    return surviving


def run_step2_af_free_regions(step1_output: dict, config: dict) -> dict:
    """
    Step 2: Parse .atr files for every patient and recording in usable_patients,
    apply the recording edge trim and AFIB buffers, and build the af_free_regions
    dictionary of surviving usable N regions.

    Sub-steps:
      2.i   — Parse raw N regions per recording (via _parse_annotation_intervals)
      2.ii  — Apply trim and buffers with clamping (via _extract_n_regions)
      2.iii — Exclude recordings that yield zero usable regions; exclude
              patients who have no surviving recordings
      2.iv  — Build output dictionary with regions in chronological order

    Returns
    -------
    dict with keys: step_2_log, af_free_regions
    """
    usable_patients = step1_output["usable_patients"]
    wfdb_dir  = config["wfdb_dir"]
    sr        = config["sampling_rate"]
    T         = config["T"]
    X         = config["X"]
    Y         = config["Y"]
    label_paf = config["label_paf"]

    af_free_regions = {}

    # Logging accumulators
    recordings_dropped_log = {}   # subject_id → {af_type, [dropped data_ids]}
    patients_excluded_log  = {}   # subject_id → {af_type, reason}

    for subject_id, patient_info in usable_patients.items():
        af_type            = patient_info["af_type"]
        surviving_recs     = {}

        for data_id, rec_info in patient_info["recordings"].items():
            duration_sec  = rec_info["recording_duration_sec"]
            record_name   = _data_id_to_record_name(data_id)
            record_path   = os.path.join(wfdb_dir, record_name)

            # Parse annotation file — if it fails, the recording is treated as
            # having no usable regions and is dropped with a printed warning.
            try:
                intervals = _parse_annotation_intervals(record_path, duration_sec, sr)
            except Exception as e:
                print(
                    f"  [Step 2] WARNING: Failed to read annotation for "
                    f"subject={subject_id}, data_id={data_id} "
                    f"(record file: {record_name}): {e}. "
                    f"This recording will be dropped."
                )
                intervals = []

            # Apply trim and buffers
            regions = _extract_n_regions(
                intervals, af_type, T, X, Y, duration_sec, label_paf
            )

            if not regions:
                # Recording dropped — log under this patient
                if subject_id not in recordings_dropped_log:
                    recordings_dropped_log[subject_id] = {
                        "af_type": af_type, "recordings_dropped": []
                    }
                recordings_dropped_log[subject_id]["recordings_dropped"].append(data_id)
                continue  # Skip — do not add to surviving_recs

            # Build region dict numbered sequentially from 1 within this recording
            region_dict = {}
            for k, region in enumerate(regions, start=1):
                region_dict[f"region_{k}"] = region

            rec_usable_dur = sum(r["duration_sec"] for r in regions)
            surviving_recs[data_id] = {
                "usable_regions_count": len(regions),
                "usable_duration_sec":  round(rec_usable_dur, 6),
                "regions":              region_dict,
            }

        # Patient-level exclusion: all recordings dropped → no usable data
        if not surviving_recs:
            patients_excluded_log[subject_id] = {
                "af_type": af_type,
                "reason":  "no_usable_regions_after_trim_and_buffer",
            }
            continue

        total_regions  = sum(r["usable_regions_count"] for r in surviving_recs.values())
        total_duration = sum(r["usable_duration_sec"]   for r in surviving_recs.values())

        af_free_regions[subject_id] = {
            "af_type":                   af_type,
            "total_usable_recordings":   len(surviving_recs),
            "total_usable_regions":      total_regions,
            "total_usable_duration_sec": round(total_duration, 6),
            "recordings":                surviving_recs,
        }

    # ── Build step_2_log ──────────────────────────────────────────────────────
    total_recs_dropped  = sum(
        len(v["recordings_dropped"]) for v in recordings_dropped_log.values()
    )
    recs_dropped_paf    = sum(
        len(v["recordings_dropped"])
        for v in recordings_dropped_log.values()
        if v["af_type"] == label_paf
    )
    recs_dropped_non_af = total_recs_dropped - recs_dropped_paf

    pat_excl_paf    = sum(1 for v in patients_excluded_log.values() if v["af_type"] == label_paf)
    pat_excl_non_af = len(patients_excluded_log) - pat_excl_paf

    surv_patients  = len(af_free_regions)
    surv_paf       = sum(1 for v in af_free_regions.values() if v["af_type"] == label_paf)
    surv_non_af    = surv_patients - surv_paf
    surv_recs      = sum(v["total_usable_recordings"] for v in af_free_regions.values())
    surv_regions   = sum(v["total_usable_regions"]    for v in af_free_regions.values())
    surv_duration  = sum(v["total_usable_duration_sec"] for v in af_free_regions.values())

    step_2_log = {
        "recordings_dropped": {
            "total_recordings_dropped":        total_recs_dropped,
            "recordings_from_PAF_patients":    recs_dropped_paf,
            "recordings_from_non_AF_patients": recs_dropped_non_af,
            "subjects": {
                sid: {
                    "af_type":             v["af_type"],
                    "recordings_dropped":  v["recordings_dropped"],
                }
                for sid, v in recordings_dropped_log.items()
            },
        },
        "patients_excluded": {
            "total_patients_excluded":  len(patients_excluded_log),
            "PAF_patients_excluded":    pat_excl_paf,
            "non_AF_patients_excluded": pat_excl_non_af,
            "subjects":                 patients_excluded_log,
        },
        "surviving_pool_summary": {
            "total_surviving_patients":    surv_patients,
            "PAF_patients":                surv_paf,
            "non_AF_patients":             surv_non_af,
            "total_surviving_recordings":  surv_recs,
            "total_surviving_regions":     surv_regions,
            "total_surviving_duration_sec": round(surv_duration, 2),
        },
    }

    step2_output = {
        "step_2_log":      step_2_log,
        "af_free_regions": af_free_regions,
    }

    print(f"[Step 2] Surviving patients:   {surv_patients} ({surv_paf} PAF, {surv_non_af} non-AF)")
    print(f"[Step 2] Recordings dropped:   {total_recs_dropped}")
    print(f"[Step 2] Patients excluded:    {len(patients_excluded_log)}")

    return step2_output

# %% ── SECTION 3: Step 3 — Patient Eligibility & Balanced Data Split ──────────

def run_step3_patient_split(step2_output: dict, config: dict) -> dict:
    """
    Step 3: Compute how many non-overlapping DT-length windows each patient
    can supply, classify patients by eligibility, construct a balanced
    patient-level dataset with equal PAF and non-AF counts, and split into
    train and eval (test) sets.

    Sub-steps:
      3.i   — Compute region_extractable_windows = floor(region_duration / DT)
              per region; sum to patient_extractable_windows.
      3.ii  — Classify patients:
                PAF:    train_eligible (>=2 windows), test_only (==1), ineligible (0)
                non-AF: eligible (>=1 window), ineligible (0)
              Note: The train_eligible threshold for PAF is >=2 (not >=1) because
              a patient contributing only 1 extractable window cannot safely be
              placed in the train set — they need at least one window to hold back
              for evaluation candidacy. Per the spec: test_only PAF patients can
              only go into the eval set.
      3.iii — Compute N_per_class = min(total_eligible_PAF, total_eligible_non_AF),
              then apply floor division to determine N_eval and N_train per class.
              Halt with an explicit error if N_train > len(PAF_train_eligible).
      3.iv  — Random selection using a single seeded random.Random instance.
              All selections within Step 3 consume the RNG in a fixed order,
              ensuring full reproducibility given the same random_seed.
      3.v   — Build the output dictionary.

    Returns
    -------
    dict with keys: config, train, eval, train_details, eval_details,
                    summary, step_3_log
    """
    af_free_regions = step2_output["af_free_regions"]
    DT           = config["DT"]
    eval_frac    = config["eval_fraction"]
    seed         = config["random_seed"]
    label_paf    = config["label_paf"]
    label_non_af = config["label_non_af"]

    # Isolated RNG for all Step 3 random selections — does not affect global state
    rng = random.Random(seed)

    # ── Step 3.i: Compute extractable windows per patient ─────────────────────
    # region_extractable_windows = floor(region_duration_sec / DT)
    # Non-overlapping packing from the start of the region; no remainder carried.
    patient_window_data = {}

    for subject_id, patient_info in af_free_regions.items():
        af_type       = patient_info["af_type"]
        total_windows = 0
        recordings_detail = {}

        for data_id, rec in patient_info["recordings"].items():
            rec_detail = {}
            for region_id, region in rec["regions"].items():
                region_windows = math.floor(region["duration_sec"] / DT)
                rec_detail[region_id] = {
                    "start_sec":                  region["start_sec"],
                    "end_sec":                    region["end_sec"],
                    "duration_sec":               region["duration_sec"],
                    "region_extractable_windows": region_windows,
                }
                total_windows += region_windows
            recordings_detail[data_id] = rec_detail

        patient_window_data[subject_id] = {
            "af_type":                    af_type,
            "patient_extractable_windows": total_windows,
            "recordings":                 recordings_detail,
        }

    # ── Step 3.ii: Classify patients by eligibility ───────────────────────────
    paf_train_eligible = []   # PAF: >= 2 extractable windows
    paf_test_only      = []   # PAF: == 1 extractable window (eval-only)
    paf_ineligible     = []   # PAF: 0 extractable windows

    non_af_eligible    = []   # non-AF: >= 1 extractable window
    non_af_ineligible  = []   # non-AF: 0 extractable windows

    for subject_id, data in patient_window_data.items():
        w = data["patient_extractable_windows"]
        if data["af_type"] == label_paf:
            if w >= 2:
                paf_train_eligible.append(subject_id)
            elif w == 1:
                paf_test_only.append(subject_id)
            else:
                paf_ineligible.append(subject_id)
        else:
            if w >= 1:
                non_af_eligible.append(subject_id)
            else:
                non_af_ineligible.append(subject_id)

    all_ineligible = paf_ineligible + non_af_ineligible

    # ── Step 3.iii: Balanced dataset size and split counts ────────────────────
    total_eligible_paf    = len(paf_train_eligible) + len(paf_test_only)
    total_eligible_non_af = len(non_af_eligible)

    N_per_class = min(total_eligible_paf, total_eligible_non_af)
    N_eval      = math.floor(eval_frac * N_per_class)
    N_train     = N_per_class - N_eval

    # Feasibility check — halts if we cannot fill the train set with train-eligible PAF
    if N_train > len(paf_train_eligible):
        raise RuntimeError(
            f"\n[Step 3] CRITICAL FAILURE: N_train_per_class = {N_train} but only "
            f"{len(paf_train_eligible)} PAF patients are train-eligible (>= 2 windows).\n"
            f"The train set cannot be filled exclusively with train-eligible PAF patients.\n"
            f"Options: reduce DT, reduce eval_fraction, or accept the dataset as-is."
        )

    # Determine limiting class
    if total_eligible_paf < total_eligible_non_af:
        limiting_class = "PAF"
    elif total_eligible_non_af < total_eligible_paf:
        limiting_class = "non_AF"
    else:
        limiting_class = "equal"

    # ── Step 3.iv: Patient selection ─────────────────────────────────────────
    # All calls to rng happen in this fixed order to guarantee reproducibility.

    # -- PAF train: draw N_train from train_eligible PAF
    paf_train_selected = rng.sample(paf_train_eligible, N_train)

    # -- PAF eval: draw N_eval from all eligible PAF not chosen for train
    #    "all eligible PAF" = paf_train_eligible + paf_test_only
    paf_not_in_train  = [s for s in (paf_train_eligible + paf_test_only)
                         if s not in set(paf_train_selected)]
    paf_eval_selected = rng.sample(paf_not_in_train, N_eval)

    # -- non-AF: select N_per_class from the eligible pool,
    #    then split into train (first N_train) and eval (remaining N_eval)
    #    by shuffling the selected pool.
    if limiting_class == "PAF":
        # non-AF pool is larger than needed — sample down to N_per_class
        non_af_pool = rng.sample(non_af_eligible, N_per_class)
    else:
        # non-AF is limiting or equal — use all eligible non-AF (exactly N_per_class)
        non_af_pool = list(non_af_eligible)

    rng.shuffle(non_af_pool)
    non_af_train_selected = non_af_pool[:N_train]
    non_af_eval_selected  = non_af_pool[N_train:]

    # Assemble final split lists, sorted for deterministic JSON output
    train_ids = sorted(paf_train_selected + non_af_train_selected)
    eval_ids  = sorted(paf_eval_selected  + non_af_eval_selected)

    # ── Sanity assertions ─────────────────────────────────────────────────────
    overlap = set(train_ids) & set(eval_ids)
    assert not overlap, (
        f"[Step 3] LEAKAGE DETECTED: {len(overlap)} patient(s) appear in both "
        f"train and eval: {overlap}"
    )
    assert len(train_ids) == 2 * N_train, (
        f"[Step 3] Train size mismatch: expected {2 * N_train}, got {len(train_ids)}"
    )
    assert len(eval_ids) == 2 * N_eval, (
        f"[Step 3] Eval size mismatch: expected {2 * N_eval}, got {len(eval_ids)}"
    )

    # ── Step 3.v: Build output ────────────────────────────────────────────────
    train_details = {sid: patient_window_data[sid] for sid in train_ids}
    eval_details  = {sid: patient_window_data[sid] for sid in eval_ids}

    train_paf    = sum(1 for sid in train_ids if patient_window_data[sid]["af_type"] == label_paf)
    train_non_af = len(train_ids) - train_paf
    eval_paf     = sum(1 for sid in eval_ids  if patient_window_data[sid]["af_type"] == label_paf)
    eval_non_af  = len(eval_ids)  - eval_paf

    # Ineligible patients log
    ineligible_subjects = {
        sid: {
            "af_type":                    patient_window_data[sid]["af_type"],
            "patient_extractable_windows": patient_window_data[sid]["patient_extractable_windows"],
            "reason":                     "no_extractable_DT_windows",
        }
        for sid in all_ineligible
    }

    # Excluded from non-limiting class (due to balance constraint)
    if limiting_class == "non_AF":
        # PAF pool had more patients than N_per_class; unselected PAF are excluded
        paf_selected_set = set(paf_train_selected + paf_eval_selected)
        paf_all_eligible = set(paf_train_eligible + paf_test_only)
        excluded_non_limiting = sorted(list(paf_all_eligible - paf_selected_set))
    elif limiting_class == "PAF":
        # non-AF pool was trimmed; the excluded entries are those not in non_af_pool
        excluded_non_limiting = sorted(
            [s for s in non_af_eligible if s not in set(non_af_pool)]
        )
    else:
        excluded_non_limiting = []

    step_3_log = {
        "ineligible_patients": {
            "total_ineligible":   len(all_ineligible),
            "PAF_ineligible":     len(paf_ineligible),
            "non_AF_ineligible":  len(non_af_ineligible),
            "subjects":           ineligible_subjects,
        },
        "eligible_pool_summary": {
            "total_eligible_PAF":     total_eligible_paf,
            "PAF_train_eligible":     len(paf_train_eligible),
            "PAF_test_only_eligible": len(paf_test_only),
            "total_eligible_non_AF":  total_eligible_non_af,
            "N_per_class":            N_per_class,
            "N_train_per_class":      N_train,
            "N_eval_per_class":       N_eval,
        },
        "limiting_class": {
            "limiting":                           limiting_class,
            "excluded_from_non_limiting_class":   len(excluded_non_limiting),
            "excluded_subject_ids":               excluded_non_limiting,
        },
    }

    step3_output = {
        "config": {
            "DT":            DT,
            "eval_fraction": eval_frac,
            "random_seed":   seed,
            "generated_at":  datetime.now(timezone.utc).isoformat(),
        },
        "train":         train_ids,
        "eval":          eval_ids,
        "train_details": train_details,
        "eval_details":  eval_details,
        "summary": {
            "train_total":    len(train_ids),
            "train_PAF":      train_paf,
            "train_non_AF":   train_non_af,
            "eval_total":     len(eval_ids),
            "eval_PAF":       eval_paf,
            "eval_non_AF":    eval_non_af,
            "total_patients": len(train_ids) + len(eval_ids),
            "total_PAF":      train_paf + eval_paf,
            "total_non_AF":   train_non_af + eval_non_af,
        },
        "step_3_log": step_3_log,
    }

    print(f"[Step 3] Train: {len(train_ids)} patients ({train_paf} PAF, {train_non_af} non-AF)")
    print(f"[Step 3] Eval:  {len(eval_ids)} patients ({eval_paf} PAF, {eval_non_af} non-AF)")
    print(f"[Step 3] Ineligible patients excluded: {len(all_ineligible)}")

    return step3_output

# %% ── SECTION 4: Step 4 — DT Window Extraction and Sub-window Slicing ────────

def _derive_region_seed(
    subject_id: str,
    data_id: str,
    region_id: str,
    global_seed: int,
) -> int:
    """
    Generate a deterministic, per-region random seed using MD5.

    The seed is derived from the combination of subject_id, data_id,
    region_id, and the global random_seed. Using MD5 ensures that:
      - The same inputs always produce the same seed (reproducibility).
      - Different combinations of inputs produce different seeds (isolation).

    The pipe character '|' is used as separator to prevent collisions between
    different combinations that would otherwise produce the same concatenated
    string (e.g. subject="1", data="23" vs subject="12", data="3").

    Callers:
      Step 4.ii (region selection): pass data_id="" and region_id=""
        → seed depends only on patient identity and global seed.
      Step 4.iii (window placement): pass all four values
        → seed depends on the specific region selected.

    Returns
    -------
    int in range [0, 2^32 - 1], suitable as a seed for random.Random.
    """
    key    = f"{subject_id}|{data_id}|{region_id}|{global_seed}"
    digest = hashlib.md5(key.encode('utf-8')).digest()
    return int.from_bytes(digest[:4], byteorder='big')


def run_step4_window_extraction(
    step3_output: dict,
    step2_output: dict,
    config: dict,
) -> dict:
    """
    Step 4: For each patient in the train and eval splits, extract one
    contiguous DT-length window from a randomly selected eligible region,
    then slice it into D-length sub-windows.

    Sub-steps:
      4.i   — Identify eligible regions per patient: duration_sec >= DT.
      4.ii  — Select one eligible region at random using _derive_region_seed
              (seed from Subject_ID + global_seed only — no data/region info).
              If only one eligible region exists, it is selected directly.
      4.iii — Draw a random window start position uniformly from
              [region_start_sec, region_end_sec − DT] using _derive_region_seed
              (seed from Subject_ID + selected Data_ID + region_id + global_seed).
      4.iv  — Slice the DT window into D-length sub-windows:
              stride = D × (1 − P), where P = Pt (train) or Pe (eval)
              n_subwindows = floor((DT − D) / stride) + 1
              subwindow_k: start = window_start + k × stride, end = start + D
      4.v   — Build the output dictionary.

    Design note: Each patient uses its own isolated random.Random instance
    seeded by _derive_region_seed. No shared mutable RNG state is used in
    Step 4 — this means sub-window positions are stable even if the patient
    order in the split lists changes.

    Returns
    -------
    dict with keys: config, train_windows, eval_windows, summary, step_4_log
    """
    DT   = config["DT"]
    D    = config["D"]
    Pt   = config["Pt"]
    Pe   = config["Pe"]
    seed = config["random_seed"]
    label_paf       = config["label_paf"]
    af_free_regions = step2_output["af_free_regions"]

    # ── Parameter validation — halts on any violation ─────────────────────────
    errors = []
    if D >= DT:
        errors.append(f"D ({D}) must be strictly less than DT ({DT}).")
    if not (0.0 <= Pt < 1.0):
        errors.append(f"Pt ({Pt}) must satisfy 0 <= Pt < 1.")
    if not (0.0 <= Pe < 1.0):
        errors.append(f"Pe ({Pe}) must satisfy 0 <= Pe < 1.")

    if errors:
        raise ValueError("[Step 4] Parameter validation FAILED:\n" + "\n".join(errors))

    config_validation_status = "passed"

    # Pre-compute strides — positivity is guaranteed by the validation above
    stride_train = D * (1.0 - Pt)
    stride_eval  = D * (1.0 - Pe)

    def _process_patient(subject_id: str, split: str) -> dict:
        """
        Steps 4.i–4.iv for a single patient.

        Parameters
        ----------
        subject_id : patient identifier (string)
        split      : "train" or "eval" — selects the overlap parameter
        """
        af_type = af_free_regions[subject_id]["af_type"]
        P       = Pt           if split == "train" else Pe
        stride  = stride_train if split == "train" else stride_eval

        # Step 4.i — Collect eligible regions (duration_sec >= DT)
        eligible = []   # list of (data_id, region_id, start_sec, end_sec)
        for data_id, rec in af_free_regions[subject_id]["recordings"].items():
            for region_id, region in rec["regions"].items():
                if region["duration_sec"] >= DT:
                    eligible.append((
                        data_id, region_id,
                        region["start_sec"], region["end_sec"]
                    ))

        # This should never happen — Step 3 guarantees at least one eligible region
        assert eligible, (
            f"[Step 4] Patient {subject_id} has no eligible regions (duration >= DT={DT}s). "
            "This is a pipeline integrity error — check Step 3 logic."
        )

        # Step 4.ii — Select one eligible region
        if len(eligible) == 1:
            selected = eligible[0]
        else:
            # Seed depends only on patient + global seed (not on specific region)
            sel_seed = _derive_region_seed(subject_id, "", "", seed)
            rng_sel  = random.Random(sel_seed)
            selected = rng_sel.choice(eligible)

        sel_data_id, sel_region_id, reg_start, reg_end = selected

        # Step 4.iii — Draw random window start position within [reg_start, reg_end - DT]
        win_seed     = _derive_region_seed(subject_id, sel_data_id, sel_region_id, seed)
        rng_win      = random.Random(win_seed)
        window_start = rng_win.uniform(reg_start, reg_end - DT)
        window_end   = window_start + DT

        # Step 4.iv — Slice into sub-windows
        n_sub = math.floor((DT - D) / stride) + 1
        subwindows = []
        for k in range(n_sub):
            sw_start = window_start + k * stride
            sw_end   = sw_start + D
            subwindows.append({
                "start_sec":    round(sw_start, 6),
                "end_sec":      round(sw_end,   6),
                "duration_sec": round(D, 6),
            })

        # Sanity: all sub-windows must lie within the DT window
        assert subwindows[0]["start_sec"]  >= round(window_start, 6) - 1e-9, \
            f"[Step 4] First sub-window starts before DT window for patient {subject_id}"
        assert subwindows[-1]["end_sec"]   <= round(window_end,   6) + 1e-9, \
            f"[Step 4] Last sub-window ends after DT window for patient {subject_id}"

        return {
            "af_type":            af_type,
            "selected_recording": sel_data_id,
            "selected_region":    sel_region_id,
            "dt_window": {
                "start_sec":    round(window_start, 6),
                "end_sec":      round(window_end,   6),
                "duration_sec": round(DT, 6),
            },
            "overlap_used":  P,
            "n_subwindows":  n_sub,
            "subwindows":    subwindows,
        }

    # ── Process all patients ──────────────────────────────────────────────────
    train_windows = {sid: _process_patient(sid, "train") for sid in step3_output["train"]}
    eval_windows  = {sid: _process_patient(sid, "eval")  for sid in step3_output["eval"]}

    # ── Build summary and log ─────────────────────────────────────────────────
    def _split_log(windows: dict) -> dict:
        total_pat   = len(windows)
        paf_pat     = sum(1 for v in windows.values() if v["af_type"] == label_paf)
        non_af_pat  = total_pat - paf_pat
        total_sub   = sum(v["n_subwindows"] for v in windows.values())
        paf_sub     = sum(v["n_subwindows"] for v in windows.values()
                          if v["af_type"] == label_paf)
        non_af_sub  = total_sub - paf_sub
        # Uniform sub-window count check — should be the same for all patients
        # given fixed DT, D, P. Report as single int if uniform, list if not.
        unique_n = list({v["n_subwindows"] for v in windows.values()})
        n_per_patient = unique_n[0] if len(unique_n) == 1 else unique_n
        return {
            "total_patients":        total_pat,
            "PAF_patients":          paf_pat,
            "non_AF_patients":       non_af_pat,
            "total_subwindows":      total_sub,
            "PAF_subwindows":        paf_sub,
            "non_AF_subwindows":     non_af_sub,
            "n_subwindows_per_patient": n_per_patient,
        }

    train_log = _split_log(train_windows)
    eval_log  = _split_log(eval_windows)

    step4_output = {
        "config": {
            "DT":           DT,
            "D":            D,
            "Pt":           Pt,
            "Pe":           Pe,
            "random_seed":  seed,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "train_windows": train_windows,
        "eval_windows":  eval_windows,
        "summary": {
            "train_total_patients":   train_log["total_patients"],
            "train_PAF_patients":     train_log["PAF_patients"],
            "train_non_AF_patients":  train_log["non_AF_patients"],
            "train_total_subwindows": train_log["total_subwindows"],
            "eval_total_patients":    eval_log["total_patients"],
            "eval_PAF_patients":      eval_log["PAF_patients"],
            "eval_non_AF_patients":   eval_log["non_AF_patients"],
            "eval_total_subwindows":  eval_log["total_subwindows"],
        },
        "step_4_log": {
            "config_validation": config_validation_status,
            "train_summary":     train_log,
            "eval_summary":      eval_log,
        },
    }

    print(f"[Step 4] Train: {train_log['total_patients']} patients, "
          f"{train_log['total_subwindows']} sub-windows "
          f"({train_log['n_subwindows_per_patient']} per patient)")
    print(f"[Step 4] Eval:  {eval_log['total_patients']} patients, "
          f"{eval_log['total_subwindows']} sub-windows "
          f"({eval_log['n_subwindows_per_patient']} per patient)")

    return step4_output

# %% ── SECTION 5: Main Execution ──────────────────────────────────────────────

def save_json(data: dict, filename: str, output_dir: str) -> None:
    """
    Serialise a dictionary to a JSON file with 2-space indentation.
    Prints the saved path for confirmation.
    """
    path = os.path.join(output_dir, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Saved → {path}")


def run_pipeline(config: dict) -> None:
    """
    Execute all four preprocessing steps in sequence and save outputs to JSON.

    Each step's output is passed directly to the next, so the pipeline is a
    linear chain: Step 1 → Step 2 → Step 3 → Step 4.
    """
    sep = "=" * 60

    print(f"\n{sep}")
    print("SHDB-AF Preprocessing Pipeline")
    print(sep)

    print("\n── Step 1: Filtering ──────────────────────────────────────")
    step1_output = run_step1_filtering(config)
    save_json(step1_output, "step1_output.json", config["output_dir"])

    print("\n── Step 2: AF-Free Region Extraction ──────────────────────")
    step2_output = run_step2_af_free_regions(step1_output, config)
    save_json(step2_output, "step2_output.json", config["output_dir"])

    print("\n── Step 3: Patient Eligibility & Balanced Split ───────────")
    step3_output = run_step3_patient_split(step2_output, config)
    save_json(step3_output, "step3_output.json", config["output_dir"])

    print("\n── Step 4: Window Extraction & Sub-window Slicing ─────────")
    step4_output = run_step4_window_extraction(step3_output, step2_output, config)
    save_json(step4_output, "step4_output.json", config["output_dir"])

    print(f"\n{sep}")
    print("Pipeline complete. All four JSON index files saved.")
    print(sep)

# Run the pipeline
run_pipeline(CONFIG)